const fs = require('fs');
const lines = [];
lines.push("import type { FieldType } from '@/types/forms'");
lines.push('');
lines.push('export interface FieldMapEntry {');
lines.push('  id: string');
lines.push('  type: FieldType');
lines.push('  labelPatterns: string[]');
lines.push('  options?: string[]');
lines.push('  required: boolean');
lines.push('  isHealthField: boolean');
lines.push('  isSensitiveField: boolean');
lines.push('}');
lines.push('');
lines.push('export const FIELD_MAP: FieldMapEntry[] = [');
function e(id,t,lp,opt,req,h,s){const L=JSON.stringify(lp);const O=opt?", options: "+JSON.stringify(opt):"";return "  { id: "+JSON.stringify(id)+", type: "+JSON.stringify(t)+", labelPatterns: "+L+O+", required: "+req+", isHealthField: "+h+", isSensitiveField: "+s+" },"; }
lines.push(e('full_name','text',['imie i nazwisko','imie','nazwisko','pelne imie'],null,true,false,false));
lines.push(e('birthday','date',['data urodzenia','urodzenia','rok urodzenia','birth','urodzin'],null,false,false,false));
lines.push(e('phone','text',['telefon','numer telefonu','kontaktowy','phone','tel'],null,true,false,false));
lines.push(e('email','text',['e-mail','email','adres email','adres e-mail'],null,false,false,false));
lines.push(e('service_type','select',['rodzaj uslugi','jaki rodzaj uslugi','jaka usluga','rodzaj zabiegu','interesuje podczas'],['Strzy\u017cenie damskie','Strzy\u017cenie m\u0119skie','Strzy\u017cenie dzieci\u0119ce','Koloryzacja (jednolita)','Refleksy / pasemka','Dekoloryzacja','Tonowanie','Keratynowe prostowanie','Kuracja regeneracyjna','Stylizacja','Inne'],false,false,false));
lines.push(e('hair_color_treated','radio',['farbowane wlosy','farbowane wlosy','czy farbowal','farbowanie'],['Tak','Nie'],false,false,false));
lines.push(e('hair_dye_location','radio',['gdzie wykonano koloryzacje','gdzie farbowal','miejsce koloryzacji'],['W salonie','Samodzielnie w domu','Nie pamietam'],false,false,false));
lines.push(e('hair_dye_product','radio',['jakimi produktami','produkty do koloryzacji','czym farbowal'],['Profesjonalnymi','Drogeryjnymi','Nie wiem'],false,false,false));
lines.push(e('hair_dye_when','radio',['kiedy ostatnio koloryzacja','kiedy ostatnio farbowal'],['mniej niz miesiac','1-3 miesiace','3-6 miesiecy','Ponad 6 miesiecy','Nigdy'],false,false,false));
lines.push(e('heat_styling_frequency','radio',['jak czesto stylizuje','cieple','suszarka','prostownica','lokuwka'],['Codziennie','Kilka razy w tygodniu','Rzadko','Nigdy'],false,false,false));
lines.push(e('hair_condition','radio',['kondycja wlosow','ocenia pan','kondycje swoich wlosow'],['Bardzo dobra','Dobra','Do poprawy','Zla','Trudno ocenic'],false,false,false));
lines.push(e('hair_problems','select',['problemy z wlosami','problemy ze skora glowy','wypadanie','lupie','rozdwojone'],['Brak problemow','Wypadanie wlosow','Przetluszczanie','Suchosc','Lupie','Podraznienie skory glowy','Rozdwojone konczyki','Inne'],false,false,false));
lines.push(e('hair_wash_frequency','radio',['jak czesto myje','mycie wlosow'],['Codziennie','Co 2 dni','2-3 razy w tygodniu','1 raz w tygodniu lub rzadziej'],false,false,false));
lines.push(e('hair_cosmetics','select',['kosmetyki do pielegnacji','jakich kosmetykow','szampon','odzywka'],null,false,false,false));
lines.push(e('service_expectation','select',['efektu oczekuje','oczekiwany efekt','cel zabiegu','cel wizyty','jakiego efektu'],null,false,false,false));
lines.push(e('skin_type','radio',['typ skory','rodzaj skory','cera'],['Normalna','Sucha','Tlusty','Mieszana','Wrazliwa'],false,false,false));
lines.push(e('skin_conditions','select',['dolegliwosci skory','zmiany skorne','stan skory','choroby skorne'],null,false,false,false));
lines.push(e('allergies','radio',['uczulony','uczulona','alergia','reakcja alergiczna','alerg','na cos uczulony'],['Tak','Nie'],false,true,false));
lines.push(e('allergy_details','textarea',['na co uczulona','na co uczulony','co wywoluje alergie','jakie alergeny','objawy alergii','czym sie objawiala','na co'],null,false,true,false));
lines.push(e('medications','radio',['leki na stale','przyjmuje leki','przyjmuje pan leki','przyjmuje jakies leki'],['Tak','Nie'],false,true,false));
lines.push(e('medication_details','textarea',['jakie leki','nazwa leku','dawka leku','ktore leki','podanie dokladnej nazwy'],null,false,true,false));
lines.push(e('pregnancy','radio',['ciaza','w ciazy','czy jest pani w ciazy'],['Tak','Nie','Nie dotyczy'],false,true,false));
lines.push(e('breastfeeding','radio',['karmi piersia','karmienie piersia'],['Tak','Nie','Nie dotyczy'],false,true,false));
lines.push(e('contraceptives','radio',['antykoncepcja','srodki antykoncepcyjne','doustna antykoncepcja','doustne srodki'],['Tak','Nie','Nie dotyczy'],false,true,false));
lines.push(e('chronic_diseases','radio',['choroby przewlekle','choruje przewlekle','cierpi na','schorzenia','aktualnie sie pan','na cos leczy'],['Tak','Nie'],false,true,true));
lines.push(e('disease_details','textarea',['jakie choroby','konkretne schorzenie','na co choruje','ktore choroby','opisz chorobe'],null,false,true,true));
lines.push(e('cancer_history','radio',['nowotw','rak','onkolog','chemioter'],['Tak','Nie'],false,true,true));
lines.push(e('pacemaker','radio',['rozrusznik','rozrusznik serca','metalowe implanty','implant'],['Tak','Nie'],false,true,true));
lines.push(e('blood_coagulation','radio',['sklonnosc do krwawien','krzepliwosc krwi','leki przeciwzakrzepowe','aspiryna','antykoagulanty','krzepn'],['Tak','Nie'],false,true,true));
lines.push(e('fainting_history','radio',['zaslabniecie','utrata przytomnosci','omdlenie','epizody zaslabniecia'],['Tak','Nie'],false,true,false));
lines.push(e('herpes','radio',['opryszczka','herpes'],['Tak','Nie'],false,true,false));
lines.push(e('sunscreen_use','radio',['ochrona przeciwsloneczna','krem z filtrem','filtr spf','spf'],['Tak codziennie','Tak raz dziennie','Tak latem','Sporadycznie','Nie'],false,false,false));
lines.push(e('gdpr_consent','checkbox',['zgoda rodo','klauzula','zgoda na przetwarzanie danych','przetwarzanie danych osobowych'],null,true,false,false));
lines.push(e('health_consent','checkbox',['zgoda na przetwarzanie danych zdrowotnych','dane o stanie zdrowia','zgoda zdrowotna','wyrazam zgode na zabieg','zgoda na zabieg'],null,true,true,false));
lines.push(e('signature','signature',['podpis','signature','zloz podpis'],null,true,false,false));
lines.push(']');
lines.push('');
fs.writeFileSync('D:/SimpliSalonCLoud/lib/forms/import-field-map.ts', lines.join('\n'), 'utf8');
console.log('Written ' + lines.length + ' lines');
